version: '3.4'

services:
  nutritionservice:
    image: ${DOCKER_REGISTRY-}nutritionservice
    build:
      context: .
      dockerfile: NutritionService/Dockerfile

  userservice:
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: .
      dockerfile: UserService/Dockerfile


  workoutservice:
    image: ${DOCKER_REGISTRY-}workoutservice
    build:
      context: .
      dockerfile: WorkoutService/Dockerfile

