---
apiVersion: v1
kind: Service
metadata:
  name: fitness
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness
  labels:
    app: fitness
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fitness
  template:
    metadata:
      labels:
        app: fitness
    spec:
      containers:
      - name: fitness
        image: |
            us-central1-docker.pkg.dev/GOOGLE_PROJECT/fitness/workoutservice:build-$GITHUB_RUN_NUMBER
            us-central1-docker.pkg.dev/GOOGLE_PROJECT/fitness/nutritionservice:build-$GITHUB_RUN_NUMBER
            us-central1-docker.pkg.dev/GOOGLE_PROJECT/fitness/userservice:build-$GITHUB_RUN_NUMBER

