---
apiVersion: v1
kind: Service
metadata:
  name: workoutservice
spec:
  type: LoadBalancer
  selector:
    app: workoutservice
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workoutservice
  labels:
    app: workoutservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workoutservice
  template:
    metadata:
      labels:
        app: workoutservice
    spec:
      containers:
      - name: workoutservice
        image: us-central1-docker.pkg.dev/GOOGLE_PROJECT/fitness/workoutservice:latest
            
        

