name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build and push Docker images
      env:
        PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        IMAGE_NAME: fitness-$GITHUB_RUN_NUMBER
      run: |
        docker build -t gcr.io/$PROJECT_ID/${{ env.IMAGE_NAME }}-workout-service:${{ github.sha }} -f WorkoutService/Dockerfile .
        docker push gcr.io/$PROJECT_ID/${{ env.IMAGE_NAME }}-workout-service:${{ github.sha }}

        docker build -t gcr.io/$PROJECT_ID/${{ env.IMAGE_NAME }}-nutrition-service:${{ github.sha }} -f NutritionService/Dockerfile .
        docker push gcr.io/$PROJECT_ID/${{ env.IMAGE_NAME }}-nutrition-service:${{ github.sha }}

        docker build -t gcr.io/$PROJECT_ID/${{ env.IMAGE_NAME }}-user-service:${{ github.sha }} -f UserService/Dockerfile .
        docker push gcr.io/$PROJECT_ID/${{ env.IMAGE_NAME }}-user-service:${{ github.sha }}
