name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set Docker image name
      run: echo IMAGE_NAME=$GITHUB_REPOSITORY-$GITHUB_RUN_NUMBER >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: gcr.io/$PROJECT_ID/${{ env.IMAGE_NAME }}:${{ github.sha }}
        builder: ${{ github.repository }}/.github/workflows/docker/Dockerfile
      env:
        PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
