name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker images
      env:
        PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        IMAGE_NAME: $GITHUB_REPOSITORY-$GITHUB_RUN_NUMBER >> $GITHUB_ENV
      run: |
        docker build -t gcr.io/$PROJECT_ID/${{ env.IMAGE_NAME }}-workout-service:${{ github.sha }} ./WorkoutService/Dockerfile
        docker push gcr.io/$PROJECT_ID/${{ env.IMAGE_NAME }}-workout-service:${{ github.sha }}

        docker build -t gcr.io/$PROJECT_ID/${{ env.IMAGE_NAME }}-nutrition-service:${{ github.sha }} ./NutritionService/Dockerfile
        docker push gcr.io/$PROJECT_ID/${{ env.IMAGE_NAME }}-nutrition-service:${{ github.sha }}

        docker build -t gcr.io/$PROJECT_ID/${{ env.IMAGE_NAME }}-user-service:${{ github.sha }} ./UserService/Dockerfile
        docker push gcr.io/$PROJECT_ID/${{ env.IMAGE_NAME }}-user-service:${{ github.sha }}
