name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Configure Docker
      uses: docker/setup-docker@v1

    - name: Set Docker image name
      run: echo IMAGE_NAME=$GITHUB_REPOSITORY-$GITHUB_RUN_NUMBER >> $GITHUB_ENV

    - name: Build Docker image
      run: docker build -t gcr.io/$PROJECT_ID/${{ env.IMAGE_NAME }}:${{ github.sha }} .
        
    - name: Authenticate with GCR
      run: |
          echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > keyfile.json
          docker login -u _json_key --password-stdin https://gcr.io < keyfile.json
          rm keyfile.json

    - name: Push Docker image to GCR
      run: docker push gcr.io/$PROJECT_ID/${{ env.IMAGE_NAME }}:${{ github.sha }}
